@host = http://localhost:5203
@contentType = application/json

###
POST {{host}}/api/auth/register
Content-Type: {{contentType}}

{
  "username": "sigmakamil",
  "email": "test22@example.com",
  "password": "Test123!"
}

###
POST {{host}}/api/auth/login
Content-Type: {{contentType}}

{
  "username": "adminuser",
  "password": "Test123!"
}

###
GET {{host}}/api/auth/logout
Content-Type: {{contentType}}

###
POST {{host}}/api/quiz
Authorization: Bearer {{authToken}}
Content-Type: {{contentType}}

###
GET {{host}}/api/quiz-management/68
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW51c2VyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoia2FtaWwucG9yZWJza2lAaWNsb3VkLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlVzZXIiLCJqdGkiOiJkYzZhMDkyNi0zYmU3LTQ2Y2MtYjRiZS01MjhkZmVjNGJmYjgiLCJzdWIiOiIzMCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiMzAiLCJleHAiOjE3NTM4NzcwNjQsImlzcyI6IkxvZ2luQ29tcG9uZW50QmFja2VuZCIsImF1ZCI6IkxvZ2luQ29tcG9uZW50QmFja2VuZFVzZXIifQ.AgJb5z8dUJK7qW3SPLx-h2lsFSUFFI0A33cX8GM0WHRNuxKY49txLZN36spf15LzTdr_DscST1CAEkzjDFr-7A