@host = http://localhost:5203
@contentType = application/json

###
POST {{host}}/api/auth/register
Content-Type: {{contentType}}

{
  "username": "sigmakamil",
  "email": "test22@example.com",
  "password": "Test123!"
}

###
POST {{host}}/api/auth/login
Content-Type: {{contentType}}

{
  "username": "adminuser",
  "password": "Test123!"
}

###
GET {{host}}/api/auth/logout
Content-Type: {{contentType}}

###
POST {{host}}/api/quiz
Authorization: Bearer {{authToken}}
Content-Type: {{contentType}}

###
GET {{host}}/api/explore/user-summary
Authorization: Bearer {{authToken}}